name: Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Configure
        run: cmake -B build -DHOP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests
        run: ctest --test-dir build -C Debug --output-on-failure
